replicaCount: 1

image:
  repository: flask-app
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

db:
  host: "mysql-b8a9210-shubham-db37.c.aivencloud.com"
  port: "27508"
  database: "defaultdb"

secret:
  dbUser: "avnadmin"
  dbPassword: "AVNS_vc6tn1nNyhWt2rv6TY5"